/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AppRouteImport } from './routes/app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppIndexRouteImport } from './routes/app.index'
import { Route as ShareTokenRouteImport } from './routes/share.$token'
import { Route as AppSitesRouteImport } from './routes/app.sites'
import { Route as ApiSplatRouteImport } from './routes/api/$'
import { Route as AppSitesIndexRouteImport } from './routes/app.sites.index'
import { Route as AppSitesNewRouteImport } from './routes/app.sites.new'
import { Route as AppSitesSiteIdRouteImport } from './routes/app.sites.$siteId'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as AppSitesSiteIdIndexRouteImport } from './routes/app.sites.$siteId.index'
import { Route as AppSitesSiteIdSettingsRouteImport } from './routes/app.sites.$siteId.settings'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const ShareTokenRoute = ShareTokenRouteImport.update({
  id: '/share/$token',
  path: '/share/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const AppSitesRoute = AppSitesRouteImport.update({
  id: '/sites',
  path: '/sites',
  getParentRoute: () => AppRoute,
} as any)
const ApiSplatRoute = ApiSplatRouteImport.update({
  id: '/api/$',
  path: '/api/$',
  getParentRoute: () => rootRouteImport,
} as any)
const AppSitesIndexRoute = AppSitesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppSitesRoute,
} as any)
const AppSitesNewRoute = AppSitesNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => AppSitesRoute,
} as any)
const AppSitesSiteIdRoute = AppSitesSiteIdRouteImport.update({
  id: '/$siteId',
  path: '/$siteId',
  getParentRoute: () => AppSitesRoute,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const AppSitesSiteIdIndexRoute = AppSitesSiteIdIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppSitesSiteIdRoute,
} as any)
const AppSitesSiteIdSettingsRoute = AppSitesSiteIdSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppSitesSiteIdRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/login': typeof LoginRoute
  '/api/$': typeof ApiSplatRoute
  '/app/sites': typeof AppSitesRouteWithChildren
  '/share/$token': typeof ShareTokenRoute
  '/app/': typeof AppIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/app/sites/$siteId': typeof AppSitesSiteIdRouteWithChildren
  '/app/sites/new': typeof AppSitesNewRoute
  '/app/sites/': typeof AppSitesIndexRoute
  '/app/sites/$siteId/settings': typeof AppSitesSiteIdSettingsRoute
  '/app/sites/$siteId/': typeof AppSitesSiteIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/api/$': typeof ApiSplatRoute
  '/share/$token': typeof ShareTokenRoute
  '/app': typeof AppIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/app/sites/new': typeof AppSitesNewRoute
  '/app/sites': typeof AppSitesIndexRoute
  '/app/sites/$siteId/settings': typeof AppSitesSiteIdSettingsRoute
  '/app/sites/$siteId': typeof AppSitesSiteIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/login': typeof LoginRoute
  '/api/$': typeof ApiSplatRoute
  '/app/sites': typeof AppSitesRouteWithChildren
  '/share/$token': typeof ShareTokenRoute
  '/app/': typeof AppIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/app/sites/$siteId': typeof AppSitesSiteIdRouteWithChildren
  '/app/sites/new': typeof AppSitesNewRoute
  '/app/sites/': typeof AppSitesIndexRoute
  '/app/sites/$siteId/settings': typeof AppSitesSiteIdSettingsRoute
  '/app/sites/$siteId/': typeof AppSitesSiteIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/app'
    | '/login'
    | '/api/$'
    | '/app/sites'
    | '/share/$token'
    | '/app/'
    | '/api/auth/$'
    | '/app/sites/$siteId'
    | '/app/sites/new'
    | '/app/sites/'
    | '/app/sites/$siteId/settings'
    | '/app/sites/$siteId/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/api/$'
    | '/share/$token'
    | '/app'
    | '/api/auth/$'
    | '/app/sites/new'
    | '/app/sites'
    | '/app/sites/$siteId/settings'
    | '/app/sites/$siteId'
  id:
    | '__root__'
    | '/'
    | '/app'
    | '/login'
    | '/api/$'
    | '/app/sites'
    | '/share/$token'
    | '/app/'
    | '/api/auth/$'
    | '/app/sites/$siteId'
    | '/app/sites/new'
    | '/app/sites/'
    | '/app/sites/$siteId/settings'
    | '/app/sites/$siteId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  LoginRoute: typeof LoginRoute
  ApiSplatRoute: typeof ApiSplatRoute
  ShareTokenRoute: typeof ShareTokenRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/': {
      id: '/app/'
      path: '/'
      fullPath: '/app/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/share/$token': {
      id: '/share/$token'
      path: '/share/$token'
      fullPath: '/share/$token'
      preLoaderRoute: typeof ShareTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/sites': {
      id: '/app/sites'
      path: '/sites'
      fullPath: '/app/sites'
      preLoaderRoute: typeof AppSitesRouteImport
      parentRoute: typeof AppRoute
    }
    '/api/$': {
      id: '/api/$'
      path: '/api/$'
      fullPath: '/api/$'
      preLoaderRoute: typeof ApiSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/sites/': {
      id: '/app/sites/'
      path: '/'
      fullPath: '/app/sites/'
      preLoaderRoute: typeof AppSitesIndexRouteImport
      parentRoute: typeof AppSitesRoute
    }
    '/app/sites/new': {
      id: '/app/sites/new'
      path: '/new'
      fullPath: '/app/sites/new'
      preLoaderRoute: typeof AppSitesNewRouteImport
      parentRoute: typeof AppSitesRoute
    }
    '/app/sites/$siteId': {
      id: '/app/sites/$siteId'
      path: '/$siteId'
      fullPath: '/app/sites/$siteId'
      preLoaderRoute: typeof AppSitesSiteIdRouteImport
      parentRoute: typeof AppSitesRoute
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/sites/$siteId/': {
      id: '/app/sites/$siteId/'
      path: '/'
      fullPath: '/app/sites/$siteId/'
      preLoaderRoute: typeof AppSitesSiteIdIndexRouteImport
      parentRoute: typeof AppSitesSiteIdRoute
    }
    '/app/sites/$siteId/settings': {
      id: '/app/sites/$siteId/settings'
      path: '/settings'
      fullPath: '/app/sites/$siteId/settings'
      preLoaderRoute: typeof AppSitesSiteIdSettingsRouteImport
      parentRoute: typeof AppSitesSiteIdRoute
    }
  }
}

interface AppSitesSiteIdRouteChildren {
  AppSitesSiteIdSettingsRoute: typeof AppSitesSiteIdSettingsRoute
  AppSitesSiteIdIndexRoute: typeof AppSitesSiteIdIndexRoute
}

const AppSitesSiteIdRouteChildren: AppSitesSiteIdRouteChildren = {
  AppSitesSiteIdSettingsRoute: AppSitesSiteIdSettingsRoute,
  AppSitesSiteIdIndexRoute: AppSitesSiteIdIndexRoute,
}

const AppSitesSiteIdRouteWithChildren = AppSitesSiteIdRoute._addFileChildren(
  AppSitesSiteIdRouteChildren,
)

interface AppSitesRouteChildren {
  AppSitesSiteIdRoute: typeof AppSitesSiteIdRouteWithChildren
  AppSitesNewRoute: typeof AppSitesNewRoute
  AppSitesIndexRoute: typeof AppSitesIndexRoute
}

const AppSitesRouteChildren: AppSitesRouteChildren = {
  AppSitesSiteIdRoute: AppSitesSiteIdRouteWithChildren,
  AppSitesNewRoute: AppSitesNewRoute,
  AppSitesIndexRoute: AppSitesIndexRoute,
}

const AppSitesRouteWithChildren = AppSitesRoute._addFileChildren(
  AppSitesRouteChildren,
)

interface AppRouteChildren {
  AppSitesRoute: typeof AppSitesRouteWithChildren
  AppIndexRoute: typeof AppIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppSitesRoute: AppSitesRouteWithChildren,
  AppIndexRoute: AppIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  LoginRoute: LoginRoute,
  ApiSplatRoute: ApiSplatRoute,
  ShareTokenRoute: ShareTokenRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
